# Generated by Django 5.1.3 on 2024-11-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PsychologyTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='ParticipantNumber',
            field=models.IntegerField(),
        ),
    ]
