# Generated by Django 5.1.3 on 2024-11-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PsychologyTest', '0005_users_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
    ]
